name: Deploy FE & BE to Render

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Deploy Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render Backend
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{"serviceId": "${{ secrets.RENDER_BACKEND_ID }}"}' \
          https://api.render.com/v1/services/${{ secrets.RENDER_BACKEND_ID }}/deploys

  frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Render Frontend
        run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -d '{"serviceId": "${{ secrets.RENDER_FRONTEND_ID }}"}' \
          https://api.render.com/v1/services/${{ secrets.RENDER_FRONTEND_ID }}/deploys
